Repository ncdulo/suppylement, pull requests merged in 2020-02, with the labels that each got.

#6 Feature/refactor data class
  pymaengda/application.py
  pymaengda/data.py
Labels: enhancement

#11 Feature/update readme
  README.md
Labels: documentation, enhancement

#13 Project rebranding
  README.md
Labels: enhancement, good first issue

#15 Finalize rebranding work
  suppylement/application.py
  suppylement/arguments.py
Labels: enhancement

#16 Continue work on README.md update
  README.md
Labels: documentation, enhancement

#17 Default to list mode when no arguments given
  suppylement/arguments.py
Labels: enhancement

#18 add step to link to /usr/local/bin
  README.md
Labels: documentation

#19 remove sh/python and path to executable
  README.md
Labels: documentation

#21 Ability to pass custom arguments to `Application`
  suppylement/application.py
  suppylement/arguments.py
Labels: enhancement

#25 Mostly complete `list` mode implementation
  suppylement/application.py
  suppylement/arguments.py
Labels: enhancement

#27 Delete mode basic implementation
  suppylement/application.py
  suppylement/arguments.py
  suppylement/data.py
Labels: enhancement

#28 Suppylement config file work
  .gitignore
  suppylement/application.py
  suppylement/configuration.py
  suppylement/suppylement_defaults.ini
Labels: enhancement
